In [1]:
import numpy as np


In [4]:
x=[2,3,5,6,7]
y =[26,45,25,36,56]

In [33]:
def gradient_descent(x,y):
    m_curr=0
    b_curr=0
    learning_rate=0.003
    n = len(x)
    itr=10000
    for i in range(itr):
        y_pred= m_curr* x + b_curr
        md =-(2/n)*sum(x*(y-y_pred))
        bd =-(1/n)*sum(y-y_pred)
        m_curr= m_curr-(learning_rate*md)
        b_curr=b_curr-(learning_rate*bd)
        print("m_curr {}, b_curr {}, iteration {} ".format(m_curr,b_curr,i))
    

In [34]:
print(x)
print(y)
x = np.array(x)
y = np.array(y)
print(x,y)
gradient_descent(x,y)

[2 3 5 6 7]
[26 45 25 36 56]
[2 3 5 6 7] [26 45 25 36 56]
m_curr 1.104, b_curr 0.11280000000000001, iteration 0 
m_curr 2.04193632, b_curr 0.2100264, iteration 1 
m_curr 2.838749790528, b_curr 0.294017599584, iteration 2 
m_curr 3.5156354356975488, b_curr 0.3667607996759616, iteration 3 
m_curr 4.090605047317534, b_curr 0.4299447482643075, iteration 4 
m_curr 4.578965267281371, b_curr 0.4850045643665326, iteration 5 
m_curr 4.993723867854125, b_curr 0.53315982998495, iteration 6 
m_curr 5.345935013651271, b_curr 0.5754469611186083, iteration 7 
m_curr 5.64499266950947, b_curr 0.6127467170468649, iteration 8 
m_curr 5.898879942099379, b_curr 0.6458075780564936, iteration 9 
m_curr 6.114380973491151, b_curr 0.6752656121213527, iteration 10 
m_curr 6.297261010909308, b_curr 0.7016613578508107, iteration 11 
m_curr 6.4524194322224115, b_curr 0.7254541718267099, iteration 12 
m_curr 6.584019788883967, b_curr 0.7470344211465605, iteration 13 
m_curr 6.695600318021048, b_curr 0.76673384479652

m_curr 6.0196075466988885, b_curr 7.850165584400115, iteration 946 
m_curr 6.018448902676689, b_curr 7.85634450350247, iteration 947 
m_curr 6.0172907363449415, b_curr 7.862520875135024, iteration 948 
m_curr 6.016133047506702, b_curr 7.868694700348058, iteration 949 
m_curr 6.014975835965106, b_curr 7.874865980191422, iteration 950 
m_curr 6.013819101523373, b_curr 7.881034715714529, iteration 951 
m_curr 6.012662843984802, b_curr 7.8872009079663625, iteration 952 
m_curr 6.011507063152774, b_curr 7.893364557995473, iteration 953 
m_curr 6.010351758830749, b_curr 7.8995256668499785, iteration 954 
m_curr 6.009196930822271, b_curr 7.9056842355775645, iteration 955 
m_curr 6.008042578930963, b_curr 7.911840265225485, iteration 956 
m_curr 6.00688870296053, b_curr 7.917993756840561, iteration 957 
m_curr 6.005735302714756, b_curr 7.924144711469184, iteration 958 
m_curr 6.004582377997509, b_curr 7.930293130157313, iteration 959 
m_curr 6.003429928612735, b_curr 7.9364390139504755, iterat

m_curr 5.175657153881003, b_curr 12.350858725443539, iteration 1812 
m_curr 5.174846457145925, b_curr 12.355182080543651, iteration 1813 
m_curr 5.174036094648182, b_curr 12.359503653193407, iteration 1814 
m_curr 5.173226066249972, b_curr 12.363823444127682, iteration 1815 
m_curr 5.1724163718135525, b_curr 12.36814145408105, iteration 1816 
m_curr 5.171607011201235, b_curr 12.372457683787779, iteration 1817 
m_curr 5.17079798427539, b_curr 12.376772133981838, iteration 1818 
m_curr 5.169989290898444, b_curr 12.381084805396892, iteration 1819 
m_curr 5.16918093093288, b_curr 12.385395698766303, iteration 1820 
m_curr 5.168372904241237, b_curr 12.38970481482313, iteration 1821 
m_curr 5.167565210686112, b_curr 12.394012154300132, iteration 1822 
m_curr 5.166757850130158, b_curr 12.398317717929762, iteration 1823 
m_curr 5.165950822436085, b_curr 12.402621506444177, iteration 1824 
m_curr 5.165144127466659, b_curr 12.406923520575226, iteration 1825 
m_curr 5.164337765084704, b_curr 12.4

m_curr 4.516565947873761, b_curr 15.865718479574776, iteration 2802 
m_curr 4.51602698393133, b_curr 15.868592714055394, iteration 2803 
m_curr 4.515488242195137, b_curr 15.871465763534976, iteration 2804 
m_curr 4.5149497225735695, b_curr 15.874337628502078, iteration 2805 
m_curr 4.514411424975053, b_curr 15.877208309445056, iteration 2806 
m_curr 4.513873349308052, b_curr 15.880077806852064, iteration 2807 
m_curr 4.5133354954810665, b_curr 15.882946121211058, iteration 2808 
m_curr 4.512797863402636, b_curr 15.885813253009786, iteration 2809 
m_curr 4.512260452981336, b_curr 15.888679202735801, iteration 2810 
m_curr 4.511723264125783, b_curr 15.891543970876452, iteration 2811 
m_curr 4.5111862967446275, b_curr 15.894407557918887, iteration 2812 
m_curr 4.510649550746559, b_curr 15.897269964350055, iteration 2813 
m_curr 4.5101130260403055, b_curr 15.900131190656703, iteration 2814 
m_curr 4.509576722534631, b_curr 15.902991237325377, iteration 2815 
m_curr 4.509040640138339, b_cur

m_curr 4.113114061035641, b_curr 18.01728230996828, iteration 3697 
m_curr 4.112741433871656, b_curr 18.019269488996084, iteration 3698 
m_curr 4.112368960335908, b_curr 18.021255848741667, iteration 3699 
m_curr 4.111996640365057, b_curr 18.023241389542807, iteration 3700 
m_curr 4.111624473895794, b_curr 18.02522611173714, iteration 3701 
m_curr 4.111252460864829, b_curr 18.027210015662167, iteration 3702 
m_curr 4.110880601208905, b_curr 18.029193101655245, iteration 3703 
m_curr 4.110508894864785, b_curr 18.031175370053596, iteration 3704 
m_curr 4.1101373417692635, b_curr 18.0331568211943, iteration 3705 
m_curr 4.109765941859157, b_curr 18.0351374554143, iteration 3706 
m_curr 4.109394695071311, b_curr 18.037117273050402, iteration 3707 
m_curr 4.109023601342594, b_curr 18.039096274439267, iteration 3708 
m_curr 4.108652660609903, b_curr 18.04107445991742, iteration 3709 
m_curr 4.10828187281016, b_curr 18.043051829821252, iteration 3710 
m_curr 4.107911237880314, b_curr 18.04502

m_curr 3.8787254967421645, b_curr 19.267250332534626, iteration 4425 
m_curr 3.8784495042450655, b_curr 19.26872216968198, iteration 4426 
m_curr 3.878173625535271, b_curr 19.27019340001435, iteration 4427 
m_curr 3.877897860565869, b_curr 19.27166402378192, iteration 4428 
m_curr 3.877622209289966, b_curr 19.273134041234766, iteration 4429 
m_curr 3.8773466716606877, b_curr 19.27460345262286, iteration 4430 
m_curr 3.877071247631179, b_curr 19.276072258196074, iteration 4431 
m_curr 3.8767959371546055, b_curr 19.277540458204175, iteration 4432 
m_curr 3.8765207401841506, b_curr 19.279008052896828, iteration 4433 
m_curr 3.8762456566730177, b_curr 19.280475042523594, iteration 4434 
m_curr 3.875970686574429, b_curr 19.281941427333937, iteration 4435 
m_curr 3.875695829841627, b_curr 19.28340720757721, iteration 4436 
m_curr 3.8754210864278718, b_curr 19.284872383502663, iteration 4437 
m_curr 3.8751464562864446, b_curr 19.28633695535945, iteration 4438 
m_curr 3.8748719393706446, b_cur

m_curr 3.6831335196050214, b_curr 20.310320490965392, iteration 5263 
m_curr 3.6829381665606755, b_curr 20.311362286921945, iteration 5264 
m_curr 3.682742894057274, b_curr 20.31240365336264, iteration 5265 
m_curr 3.6825477020616115, b_curr 20.313444590464563, iteration 5266 
m_curr 3.682352590540496, b_curr 20.31448509840472, iteration 5267 
m_curr 3.6821575594607485, b_curr 20.315525177360048, iteration 5268 
m_curr 3.681962608789205, b_curr 20.31656482750741, iteration 5269 
m_curr 3.6817677384927134, b_curr 20.317604049023597, iteration 5270 
m_curr 3.6815729485381374, b_curr 20.31864284208533, iteration 5271 
m_curr 3.6813782388923535, b_curr 20.319681206869245, iteration 5272 
m_curr 3.681183609522251, b_curr 20.320719143551923, iteration 5273 
m_curr 3.680989060394734, b_curr 20.32175665230986, iteration 5274 
m_curr 3.6807945914767193, b_curr 20.322793733319482, iteration 5275 
m_curr 3.6806002027351377, b_curr 20.323830386757145, iteration 5276 
m_curr 3.680405894136934, b_cu

m_curr 3.5505489152176555, b_curr 21.017379371027957, iteration 6059 
m_curr 3.5504082246911577, b_curr 21.01812965788487, iteration 6060 
m_curr 3.5502675921691202, b_curr 21.018879635410478, iteration 6061 
m_curr 3.550127017627629, b_curr 21.019629303732312, iteration 6062 
m_curr 3.549986501042779, b_curr 21.020378662977855, iteration 6063 
m_curr 3.549846042390676, b_curr 21.02112771327453, iteration 6064 
m_curr 3.549705641647435, b_curr 21.021876454749716, iteration 6065 
m_curr 3.5495652987891817, b_curr 21.022624887530732, iteration 6066 
m_curr 3.5494250137920504, b_curr 21.023373011744848, iteration 6067 
m_curr 3.549284786632186, b_curr 21.024120827519283, iteration 6068 
m_curr 3.5491446172857435, b_curr 21.0248683349812, iteration 6069 
m_curr 3.549004505728887, b_curr 21.025615534257714, iteration 6070 
m_curr 3.5488644519377903, b_curr 21.02636242547588, iteration 6071 
m_curr 3.548724455888638, b_curr 21.02710900876271, iteration 6072 
m_curr 3.5485845175576243, b_curr

m_curr 3.454860735147987, b_curr 21.527673743047306, iteration 6857 
m_curr 3.4547594953320386, b_curr 21.528213643673123, iteration 6858 
m_curr 3.4546582972556514, b_curr 21.52875332170652, iteration 6859 
m_curr 3.4545571409016174, b_curr 21.529292777239274, iteration 6860 
m_curr 3.4544560262527346, b_curr 21.529832010363112, iteration 6861 
m_curr 3.454354953291809, b_curr 21.530371021169735, iteration 6862 
m_curr 3.4542539220016533, b_curr 21.5309098097508, iteration 6863 
m_curr 3.454152932365087, b_curr 21.531448376197925, iteration 6864 
m_curr 3.4540519843649373, b_curr 21.531986720602692, iteration 6865 
m_curr 3.4539510779840383, b_curr 21.53252484305665, iteration 6866 
m_curr 3.453850213205231, b_curr 21.5330627436513, iteration 6867 
m_curr 3.453749390011363, b_curr 21.533600422478113, iteration 6868 
m_curr 3.45364860838529, b_curr 21.53413787962852, iteration 6869 
m_curr 3.453547868309874, b_curr 21.534675115193917, iteration 6870 
m_curr 3.4534471697679847, b_curr 2

m_curr 3.3806229242278936, b_curr 21.923575693277503, iteration 7730 
m_curr 3.3805522914773976, b_curr 21.923952369843324, iteration 7731 
m_curr 3.380481687847658, b_curr 21.924328891111404, iteration 7732 
m_curr 3.380411113326669, b_curr 21.92470525714577, iteration 7733 
m_curr 3.3803405679024294, b_curr 21.925081468010426, iteration 7734 
m_curr 3.380270051562943, b_curr 21.925457523769342, iteration 7735 
m_curr 3.380199564296219, b_curr 21.925833424486466, iteration 7736 
m_curr 3.3801291060902705, b_curr 21.926209170225718, iteration 7737 
m_curr 3.3800586769331167, b_curr 21.926584761050997, iteration 7738 
m_curr 3.379988276812781, b_curr 21.926960197026165, iteration 7739 
m_curr 3.3799179057172926, b_curr 21.92733547821507, iteration 7740 
m_curr 3.379847563634684, b_curr 21.927710604681526, iteration 7741 
m_curr 3.3797772505529946, b_curr 21.928085576489323, iteration 7742 
m_curr 3.379706966460267, b_curr 21.928460393702224, iteration 7743 
m_curr 3.3796367113445505, b_

m_curr 3.3323801233820647, b_curr 22.18084915948987, iteration 8532 
m_curr 3.3323293803689515, b_curr 22.18111976630873, iteration 8533 
m_curr 3.3322786582763735, b_curr 22.18139026156071, iteration 8534 
m_curr 3.332227957095705, b_curr 22.181660645291814, iteration 8535 
m_curr 3.332177276818325, b_curr 22.18193091754802, iteration 8536 
m_curr 3.332126617435615, b_curr 22.182201078375282, iteration 8537 
m_curr 3.3320759789389602, b_curr 22.182471127819547, iteration 8538 
m_curr 3.33202536131975, b_curr 22.18274106592673, iteration 8539 
m_curr 3.331974764569377, b_curr 22.18301089274274, iteration 8540 
m_curr 3.3319241886792375, b_curr 22.183280608313453, iteration 8541 
m_curr 3.331873633640731, b_curr 22.18355021268474, iteration 8542 
m_curr 3.33182309944526, b_curr 22.183819705902444, iteration 8543 
m_curr 3.331772586084232, b_curr 22.184089088012392, iteration 8544 
m_curr 3.3317220935490575, b_curr 22.184358359060393, iteration 8545 
m_curr 3.3316716218311497, b_curr 22.

m_curr 3.2916340758808214, b_curr 22.398143277810217, iteration 9507 
m_curr 3.29160013181325, b_curr 22.39832429772963, iteration 9508 
m_curr 3.2915662017402765, b_curr 22.398505243017418, iteration 9509 
m_curr 3.291532285656131, b_curr 22.39868611370435, iteration 9510 
m_curr 3.2914983835550458, b_curr 22.398866909821184, iteration 9511 
m_curr 3.2914644954312564, b_curr 22.39904763139866, iteration 9512 
m_curr 3.291430621279, b_curr 22.39922827846751, iteration 9513 
m_curr 3.2913967610925163, b_curr 22.399408851058457, iteration 9514 
m_curr 3.2913629148660477, b_curr 22.399589349202206, iteration 9515 
m_curr 3.291329082593838, b_curr 22.399769772929446, iteration 9516 
m_curr 3.291295264270135, b_curr 22.399950122270862, iteration 9517 
m_curr 3.291261459889187, b_curr 22.400130397257122, iteration 9518 
m_curr 3.2912276694452465, b_curr 22.40031059791888, iteration 9519 
m_curr 3.291193892932567, b_curr 22.40049072428678, iteration 9520 
m_curr 3.2911601303454048, b_curr 22.